var iol=iol||{};iol.iolcookcs={};iol.dmp2={};iol.track={};iol.iolcookcs.ready=function(a){if("complete"==document.readyState)return a();window.addEventListener?window.addEventListener("load",a,!1):window.attachEvent?window.attachEvent("onload",a):window.onload=a};
iol.iolcookcs.ready(function(){(function(a){if(a.cookieChoices)return a.iol.cookieChoices;var b=a.document,d="textContent"in b.body,c=function(){function c(a,b,e){d?a.textContent=b:a.innerText=b;a.style.cssText=e}function l(a,p){var g=b.createElement("span");c(g,a,p);return g}function n(a,p,e){var g=b.createElement("a");c(g,p);g.id=a;g.href="#";g.style.cssText=e;return g}function m(a,p,e,f){var g=b.createElement("a");c(g,p);g.id=a;g.href=e;g.style.cssText=f;return g}function k(a,b,e){if(!a)return!1;
if(a.addEventListener)return a.addEventListener(b,e,!0),!0;if(a.attachEvent)return a.attachEvent("on"+b,e)}function q(a,b,e){if(!a)return!1;if(a.addEventListener)return a.removeEventListener(b,e),!0;if(a.attachEvent)return a.detachEvent("on"+b,e)}function f(a){try{0<b.location.href.indexOf("log=true")&&console.log("[optin]"+a)}catch(p){}}function r(){return!0}function z(){return t("optin_ok")}function A(){return t("optin_close")}function t(a){try{f("_dismissLinkClick "+a);var g=B+"?value=1&r="+Math.floor(10*
Math.random()+1),e=b.createElement("IFRAME");e.setAttribute("src",g);e.style.width="0px";e.style.height="0px";e.style.display="none";b.body.appendChild(e);f("createPolicyCookie created");x();f("_dismissLinkClick  END "+a)}catch(H){}return!1}function C(g){try{null!=b.getElementById("cookieChoiceInfo")?(f("register Scroll"),t("optin_Scroll"),f(q(a,"scroll",u)),v(g),f("register  1END Scroll")):f("banner not present Scroll")}catch(p){f("detect tree check")}}function D(){a.setTimeout(function(){f("start 1.44");
try{$("cookieChoiceInfo").fadeIn(1E3)}catch(g){f("jquery not found")}try{b.getElementById("cookieChoiceInfo").style.opacity=1}catch(g){}},2E3)}function u(g){if(null!=b.getElementById("cookieChoiceInfo")){f("register 1.43");var c=0;try{for(var e=g.target;e;){if(e.id&&("cookieChoiceDismiss2"==e.id||"cookieChoiceDismiss"==e.id)){c=1;f("found OK or x");break}else if(e.id&&"cookieChoiceInfo"==e.id){f("found cookieConsentId");c=1;break}e=e.parentNode}}catch(w){f("detect tree check")}0==c&&t("optin_click");
try{if(0==c)for(var d=g.target;d;){if(d.href&&""!==d.href){f("href event "+d.href);g.preventDefault();break}else f("rec else:"+d);d=d.parentNode}}catch(w){f("errr evnet listener")}f(q(a,"click",u));0==c&&v(g);f("register END ")}else f("banner not present")}function v(a){a.stopPropagation?a.stopPropagation():a.returnValue=!1}function E(a){v(a)}function x(){if(null!=b.getElementById("cookieChoiceInfo")){var a=b.getElementById("cookieChoiceInfo");a.parentNode.removeChild(a)}}function F(){if(null==y("policy_cookie"))return!0;
var a=y("policy_cookie").split("_")[0],c=a.charAt(1),e=a.charAt(2);if(a.length!=G.length){if("1"==c||"1"==e)return f(c+","+e),!1;a=iolcookcs.policyCookieName;c=new Date;c.setTime(c.getTime()+-864E5);c="; expires="+c.toGMTString();b.cookie=a+"="+c+"; path=/";return!0}return!1}function y(a){a+="=";for(var c=b.cookie.split(";"),e=0;e<c.length;e++){for(var d=c[e];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null}var G="DataRecs geo vlocal Advertising tmp1 tmp2 af xedge".split(" "),
B=("https:"==b.location.protocol?"https:":"http:")+"//privacy.italiaonline.it/common/cookie/api/set_policy_cookie.php";return{displayCookieBanner:function(){if(F())try{x();if(iol&&iol.overload){f("oveloading tooltip");var c=iol.overload._createHeaderElement("cookieChoiceInfo","cookieChoiceDismiss","cookieChoiceDismiss2","https://privacy.italiaonline.it/common/cookie/privacy_detail.php?from=banner","leggiLinkIdp")}else{f("base tooltip");var d=b.createElement("div");d.id="cookieChoiceInfo";d.style.cssText=
"opacity:0; text-align:left; font-family: Arial,Helvetica,sans-serif; position: fixed; z-index: 100000000; background: none repeat scroll 0% 0% rgb(22, 121, 195); padding: 5px 25px; line-height: 14px; font-size:14px;  left: 0px; top: 0px; color:#fff;margin: 10px 20px;";var e=b.createElement("div");e.style.cssText="margin: px 01px";e.appendChild(n("cookieChoiceDismiss","X","vertical-align: middle; color: rgb(255, 255, 255); font-weight: bold; font-family: Tahoma,Geneva,sans-serif; font-size: 15px; text-decoration: none; position:absolute; right:7px; top:5px"));
e.appendChild(l("Questo sito utilizza cookie anche di terzi per inviarti pubblicita' e servizi in linea con le tue preferenze. Se vuoi saperne di piu' o negare il consenso a tutti o ad alcuni cookie, ","vertical-align:middle;color: rgb(255, 255, 255);"));e.appendChild(m("leggiLinkIdp","leggi qui","https://privacy.italiaonline.it/common/cookie/privacy_detail.php?from=banner","vertical-align:middle;color:#FFF; font-weight:bold; text-decoration:none"));e.appendChild(l(". Chiudendo questo banner, scorrendo questa pagina o cliccando qualunque elemento acconsenti all'uso dei cookie.",
"vertical-align:middle;color: rgb(255, 255, 255);"));e.appendChild(n("cookieChoiceDismiss2","OK","vertical-align: middle; color: rgb(22, 121, 195); font-weight: bold; background: none repeat scroll 0% 0% rgb(238, 238, 238); text-decoration: none; display: inline-block; padding:1px 10px; line-height: 16px; margin: 2px 0px 0px 10px;"));d.appendChild(e);c=d}var h=b.createDocumentFragment();h.appendChild(c);b.body.appendChild(h.cloneNode(!0));b.getElementById("cookieChoiceDismiss").onclick=A;b.getElementById("cookieChoiceDismiss2").onclick=
z;b.getElementById("leggiLinkIdp").onclick=r;k(a,"click",u);k(a,"scroll",C);D();k("cookieChoiceInfo","click",E)}catch(w){f("showBar problem ")}}}}();a.iolp={cookieChoices:c};return c})(this);iolp.cookieChoices.displayCookieBanner();window.setTimeout(function(){try{iol.dmp2.semtrack()}catch(a){iol.dmp2.log("semtrackAsync")}},6E3)});
iol.iolcookcs.trackCookie=function(a){try{var b=("https:"==document.location.protocol?"https:":"http:")+"//privacy.italiaonline.it/common/cookie/api/set_policy_cookie.php?trvalue="+a+"&r="+Math.floor(10*Math.random()+1),d=document.createElement("IFRAME");d.setAttribute("src",b);d.style.width="0px";d.style.height="0px";d.style.display="none";window.setTimeout(function(){document.body.appendChild(d)},3E3)}catch(c){}};
iol.iolcookcs.isCookieEnable=function(a){for(var b="DataRecs geo vlocal Advertising tmp1 tmp2 af xedge".split(" "),d="",c=document.cookie.split(";"),h=0;h<c.length;h++){for(var l=c[h];" "==l.charAt(0);)l=l.substring(1,l.length);0==l.indexOf("policy_cookie=")&&(d=l.substring(14,l.length))}if(null!=d&&""!=d){d=d.split("_")[0];c=null;for(index=0;index<b.length;++index)if(b[index]==a){c=index;break}a=null!=c?d.charAt(c):null}else return!0;return"1"==a?!0:!1};
iol.dmp2.semtrackAsync=function(a){try{var b=iol.dmp2.detectbcp();if("undefined"!=typeof a.stes){if("string"==typeof a.stes.tag)b.add("genp","sem:"+a.stes.tag),iol.dmp2.log(a.stes.tag);else for(var d=0;d<a.stes.tag.length;d++)b.add("genp","sem:"+a.stes.tag[d]),iol.dmp2.log(a.stes.tag[d]);b.bcp()}else iol.dmp2.log("nessun val")}catch(c){iol.dmp2.log("semtrackAsync")}};
iol.dmp2.semtrack=function(){try{iol.dmp2.log("Start semtrack "+document.location.href.length),"undefined"!=typeof iol.dmp2.detectbcp()?35<document.location.href.length&&(iol.dmp2.log("url OK"),iol.dmp2.getSemInfo()):iol.dmp2.log("sem stop bcp nt")}catch(a){iol.dmp2.log("semtrack")}};
iol.dmp2.detectbcp=function(){var a;"undefined"!=typeof _cc6200?a=_cc6200:"undefined"!=typeof _cc6206?a=_cc6206:"undefined"!=typeof _cc6202?a=_cc6202:"undefined"!=typeof _cc6205?a=_cc6205:"undefined"!=typeof _cc6207?a=_cc6207:"undefined"!=typeof _cc6204?a=_cc6204:"undefined"!=typeof _cc6233?a=_cc6233:"undefined"!=typeof _cc6328?a=_cc6328:"undefined"!=typeof _cc6775?a=_cc6775:"undefined"!=typeof _cc6235?a=_cc6235:"undefined"!=typeof _cc6367?a=_cc6367:"undefined"!=typeof _cc6232?a=_cc6232:"undefined"!=
typeof _cc6348?a=_cc6348:"undefined"!=typeof _cc8516?a=_cc8516:iol.dmp2.log("bcp non trovato");return a};iol.dmp2.getSemUrl=function(){try{var a=document.location.href;-1<a.indexOf("https://")&&(a="");-1<a.indexOf("?")&&(a=a.substring(0,a.indexOf("?")));iol.dmp2.log("clean "+a);if(""!=a)return"https://tuttosu.virgilio.it/all-about-api/tags_service_tutto_su.php?id="+encodeURIComponent(a)+"&format=jsonp&callback=iol.dmp2.semtrackAsync";iol.dmp2.log("https://tuttosu.virgilio.it/index.php");return""}catch(b){}};
iol.dmp2.log=function(a){try{0<document.location.href.indexOf("log=true")&&console.log("[dmp]"+a)}catch(b){}};iol.dmp2.getSemInfo=function(){try{var a=this.getSemUrl();if(""!=a){var b=document.createElement("script");b.type="text/javascript";b.src=a;window.setTimeout(function(){try{document.body.appendChild(b)}catch(d){}},3E3)}}catch(d){iol.dmp2.log("getSemInfo")}};
iol.track.regTracking=function(){try{iol.dmp2.log("start timeout track"),35<document.location.href.length?window.setTimeout(function(){try{iol.track.Tracking()}catch(a){}},3E3):iol.dmp2.log("no track")}catch(a){iol.dmp2.log("regTracking")}};
iol.track.Tracking=function(){try{iol.dmp2.log("track ");var a=window.location.href,b=document.referrer;-1<a.indexOf("?")&&(a=a.substring(0,a.indexOf("?")));b+="/";var d="";iol.dmp2.log("track referer "+b);iol.dmp2.log("track url "+a);if(-1!=b.indexOf("google.")||-1!=b.indexOf("bing.")){iol.dmp2.log("track seo ");var c="",h=b.indexOf("&q=");-1==h&&(h=b.indexOf("?q="));iol.dmp2.log("track seo 2 "+h);if(-1!=h){var l=b.indexOf("&",h+1);c=b.substring(h+1,l)+"&";c=c.replace("q=","q=seo_")}iol.dmp2.log("track seo 3 "+
c);var n=b.indexOf("http://"),m=b.indexOf("/",7);-1==n&&(n=b.indexOf("https://"),m=b.indexOf("/",8),-1==m&&(m=b.length),iol.dmp2.log("track seo 3 https "+n+", "+m));var k=b.substring(0,m).replace("http://","").replace("https://","");try{-1!=k.indexOf("http")&&(k=10<k.length?"f"+k.substring(0,9):"f"+k)}catch(r){}""==c&&(c="q="+k+"&");d=c+"d="+k;iol.dmp2.log("track seo 4 "+d)}else if(b.indexOf("facebook.")||b.indexOf("twitter.")){iol.dmp2.log("track social ");n=b.indexOf("http://");m=b.indexOf("/",
7);-1==n&&(b.indexOf("https://"),m=b.indexOf("/",8));k=b.substring(0,m).replace("http://","").replace("https://","");try{-1!=k.indexOf("http")&&(k=10<k.length?"f"+k.substring(0,9):"f"+k)}catch(r){}d="q="+k+"&d="+k}h=c="";-1!=a.indexOf("dilei.it")?h="IVD_":-1!=a.indexOf("motori.virgilio.it")?h="IVM_":-1!=a.indexOf("quifinanza.it")?h="IVF_":-1!=a.indexOf("siviaggia.it")?h="IVV_":-1!=a.indexOf("supereva.it")?(a=a.replace(RegExp("-","g"),"/"),iol.dmp2.log("Adapting supereva -/"),h="ISE_"):-1!=a.indexOf("sportstadio.it")?
h="IWN_":iol.dmp2.log("no dominio track");if(h)if(-1!=a.indexOf("/attachment/")){var q=a.indexOf("/attachment/");c=a.substring(a.lastIndexOf("/",q-1)+1,q).replace("/","")}else c=a.substring(a.lastIndexOf("/",a.length-2)+1).replace("/","");q=/^\d+$/;""==c||q.test(c)?c=h+c:(iol.dmp2.log("ID not detected"),c="");if(""!=c&&""!=b&&"http:"==document.location.protocol){var f=document.createElement("img");f.type="text/javascript";f.src="https://kpi.plug.it/tracks/bi/images/RT_A.gif?link="+a+"&"+d+"&id=C_"+
c+"&rand="+Math.floor(1E7*Math.random()+1);iol.dmp2.log("track url.src "+f.src);document.body.appendChild(f)}}catch(r){iol.dmp2.log("Tracking")}};iol.track.regTracking();
